c3p0.driverClass=com.mysql.jdbc.Driver
c3p0.jdbcUrl=jdbc:mysql://localhost:3306/salt-fish?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
c3p0.user=root
c3p0.password=your_password_here

jdbc.c3p0.testConnectionOnCheckout=false
jdbc.c3p0.testConnectionOnCheckin=true
jdbc.c3p0.idleConnectionTestPeriod=3600

jdbc.c3p0.initialPoolSize=10
jdbc.c3p0.minPoolSize=10
jdbc.c3p0.maxPoolSize=100

jdbc.c3p0.maxIdleTime=3600